import { defineConfig } from "oxlint"
import core from "ultracite/oxlint/core"

export default defineConfig({
  extends: [core],
  ignorePatterns: [...core.ignorePatterns],
  rules: {
    "no-bitwise": "off",
    "no-plusplus": "off",
    "no-await-in-loop": "off",
    complexity: "off",
    "sort-keys": "off",
    "sort-vars": "off",
    "func-style": "off",
    "no-inner-declarations": "off",
    curly: "off",
    "require-unicode-regexp": "off",
    "prefer-named-capture-group": "off",
    "unicorn/prefer-query-selector": "off",
    "unicorn/prefer-number-coercion": "off",
    "unicorn/numeric-separators-style": "off",
    "unicorn/prefer-string-replace-all": "off",
    "unicorn/prefer-number-properties": "off",
    "unicorn/prefer-dom-node-append": "off",
    "unicorn/no-new-array": "off",
    "unicorn/prefer-math-trunc": "off",
    "@typescript-eslint/no-explicit-any": "off",
    "eslint/prefer-template": "off",
    "eslint/prefer-exponentiation-operator": "off",
    "eslint/no-use-before-define": "off",
    "eslint/require-await": "off",
    "promise/prefer-await-to-then": "off",
    "promise/avoid-new": "off",
    "promise/param-names": "off",
    "promise/prefer-await-to-callbacks": "off",
    "unicorn/no-await-expression-member": "off",
    "unicorn/consistent-function-scoping": "off",
    "unicorn/prefer-optional-catch-binding": "off",
    "unicorn/no-negated-condition": "off",
    "typescript/no-non-null-assertion": "off",
    "typescript/prefer-function-type": "off",
    "eslint/no-empty-function": "off",
    "eslint/no-unneeded-ternary": "off",
    "eslint/no-negated-condition": "off",
    "eslint/prefer-destructuring": "off",
    "eslint/no-promise-executor-return": "off",
    "import/consistent-type-specifier-style": "off",
    "import/no-named-as-default-member": "off",
  },
})
